org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8 -XX:-UsePerfData
android.useAndroidX=true
kotlin.code.style=official
kotlin.compiler.execution.strategy=in-process
beatweaveGroup=io.github.adrielggmotion.beatweave
beatweaveVersion=0.10.0
beatweaveRepositoryUrl=https://github.com/adrielGGmotion/BeatWeave
