package org.metrolist.beatweave

import kotlin.math.floor
import kotlin.math.max
import kotlin.math.sqrt

/**
 * Measured relative spectral-attack energy, independent of any proposed beat clock. Bands are
 * 40–180, 180–1000, 1000–4000 and 4000–10000 Hz. Each positive magnitude difference is divided by
 * total measured 40–10000 Hz magnitude, so quiet audio does not lose evidence merely because of its
 * gain. Frames use the analyzer's centered symmetric Hann window; unavailable frequencies, DC and
 * Nyquist are omitted. The first frame has zero attack because no preceding observation exists.
 */
class AcousticAttackFeatures
internal constructor(
    bands: Array<FloatArray>,
    val hopSeconds: Double,
    val durationSeconds: Double,
) {
    private val values = Array(bands.size) { bands[it].copyOf() }
    val frameCount: Int = values.firstOrNull()?.size ?: 0

    init {
        require(values.size == 4 && frameCount > 0) { "Four nonempty attack bands required" }
        require(hopSeconds.isFinite() && hopSeconds > 0.0)
        require(durationSeconds.isFinite() && durationSeconds > 0.0)
        require(
            values.all { row -> row.size == frameCount && row.all { it.isFinite() && it >= 0f } }
        ) {
            "Attack features must be finite, nonnegative and equally sized"
        }
        require(
            durationSeconds >= (frameCount - 1) * hopSeconds - 1e-9 &&
                durationSeconds <= frameCount * hopSeconds + 1e-9
        ) {
            "Attack frames must cover the source duration at the stated hop"
        }
    }

    /** Defensive snapshot for diagnostics; modifying it cannot alter an assessment. */
    fun band(bandIndex: Int): FloatArray {
        require(bandIndex in 0..3)
        return values[bandIndex].copyOf()
    }

    internal fun interpolate(band: Int, seconds: Double): Double {
        val position = seconds / hopSeconds
        val left = floor(position).toInt().coerceIn(0, frameCount - 1)
        val right = (left + 1).coerceAtMost(frameCount - 1)
        val weight = (position - left).coerceIn(0.0, 1.0)
        return values[band][left] * (1.0 - weight) + values[band][right] * weight
    }
}

/** Reuses the analyzer's FFT; its working memory is four accumulated band values. */
internal class AcousticAttackFeatureCollector(
    frames: Int,
    private val hopSeconds: Double,
    private val durationSeconds: Double,
) {
    private val bands = Array(4) { FloatArray(frames) }
    private val rise = DoubleArray(4)
    private var total = 0.0
    private var currentFrame = 0

    fun record(frame: Int, hz: Double, magnitude: Double, previousMagnitude: Double) {
        check(frame == currentFrame && frame in bands[0].indices)
        require(hz.isFinite() && magnitude.isFinite() && previousMagnitude.isFinite())
        require(magnitude >= 0.0 && previousMagnitude >= 0.0)
        if (hz !in 40.0..10000.0) return
        total += magnitude
        if (frame == 0) return
        val delta = max(0.0, magnitude - previousMagnitude)
        if (hz in 40.0..180.0) rise[0] += delta
        if (hz in 180.0..1000.0) rise[1] += delta
        if (hz in 1000.0..4000.0) rise[2] += delta
        if (hz in 4000.0..10000.0) rise[3] += delta
    }

    fun finishFrame(frame: Int) {
        check(frame == currentFrame && frame in bands[0].indices)
        for (band in 0..3) {
            bands[band][frame] = if (total > 0.0) (rise[band] / total).toFloat() else 0f
            rise[band] = 0.0
        }
        total = 0.0
        currentFrame++
    }

    fun finish(): AcousticAttackFeatures {
        check(currentFrame == bands[0].size) { "All attack feature frames must be measured" }
        return AcousticAttackFeatures(bands, hopSeconds, durationSeconds)
    }
}

/** An eight-interval context; its boundaries do not certify every interval it contains. */
data class AcousticPulseWindow(
    val startBeat: Int,
    val endBeatExclusive: Int,
    val startSeconds: Double,
    val endSeconds: Double,
    val activeIntervalFraction: Double,
    val statistic: Double,
    val nullMean: Double,
    val nullStd: Double,
    val pValue: Double,
    val supported: Boolean,
) {
    /** The one interval whose local context this window describes. */
    val centerInterval: Int
        get() = startBeat + 4
}

enum class AcousticPulseIssue {
    /** The source clock lacks an eight-interval neighborhood for a requested interval. */
    INSUFFICIENT_CONTEXT,
    /** Measured attacks are not consistently recurring in a requested interval's neighborhood. */
    NONRECURRING_ATTACKS,
    /** The requested range itself has too few attacks, regardless of its neighbors. */
    INSUFFICIENT_LOCAL_ATTACKS,
}

data class AcousticPulseRangeAssessment(
    val startBeat: Int,
    val endBeatExclusive: Int,
    val supported: Boolean,
    val issues: Set<AcousticPulseIssue>,
    val activeIntervalFraction: Double,
)

/**
 * Necessary acoustic corroboration, not a probability that the beats or meter are correct. A
 * constant phase offset and integer-related pulse levels can also have recurring attacks. Clock
 * indices refer to the original supplied observations. No event is moved or inserted.
 */
class AcousticPulseReport
internal constructor(
    beatSeconds: DoubleArray,
    windows: List<AcousticPulseWindow>,
    intervalContrasts: DoubleArray,
) {
    private val sourceClock = beatSeconds.copyOf()
    val beatCount: Int
        get() = sourceClock.size

    private val windowValues = windows.toList()
    private val contrasts = intervalContrasts.copyOf()
    val windows: List<AcousticPulseWindow>
        get() = windowValues.toList()

    /** Interval centers with complete measured context; may still have failed evidence. */
    val evaluatedIntervalRange: IntRange?
        get() =
            if (windowValues.isEmpty()) null
            else windowValues.first().centerInterval..windowValues.last().centerInterval

    val intervalContrasts: DoubleArray
        get() = contrasts.copyOf()

    val activeIntervals: BooleanArray
        get() = BooleanArray(contrasts.size) { isActive(it) }

    /** Prevents applying a result to a different clock, including altered timestamps. */
    fun requireClock(seconds: DoubleArray) {
        require(sourceClock.contentEquals(seconds)) {
            "Acoustic evidence belongs to a different source clock"
        }
    }

    private fun isActive(interval: Int) =
        contrasts[interval] >= AcousticPulseEvidence.MINIMUM_CONTRAST

    fun supportsRange(startBeat: Int, endBeatExclusive: Int): Boolean =
        assessRange(startBeat, endBeatExclusive).supported

    /**
     * Requires every requested interval's own evaluated context, at least half of the requested
     * intervals to contain attacks, and no two adjacent requested intervals to both lack attacks.
     * An isolated rest can pass; an inaudible bar cannot borrow its neighbors' evidence. Missing
     * edge context abstains. [endBeatExclusive] includes the final boundary event: a bar from beat
     * 4 to beat 8 is queried as (4, 9), covering intervals 4, 5, 6 and 7.
     */
    fun assessRange(startBeat: Int, endBeatExclusive: Int): AcousticPulseRangeAssessment {
        require(
            startBeat >= 0 &&
                endBeatExclusive >= 0 &&
                endBeatExclusive <= beatCount &&
                endBeatExclusive.toLong() - startBeat.toLong() >= 2L
        ) {
            "A pulse range needs at least two in-bounds boundary observations"
        }
        val issues = mutableSetOf<AcousticPulseIssue>()
        var active = 0
        var previousInactive = false
        for (interval in startBeat until endBeatExclusive - 1) {
            val windowIndex = interval - 4
            if (windowIndex !in windowValues.indices) {
                issues += AcousticPulseIssue.INSUFFICIENT_CONTEXT
            } else if (!windowValues[windowIndex].supported) {
                issues += AcousticPulseIssue.NONRECURRING_ATTACKS
            }
            val inactive = !isActive(interval)
            if (!inactive) active++
            if (inactive && previousInactive)
                issues += AcousticPulseIssue.INSUFFICIENT_LOCAL_ATTACKS
            previousInactive = inactive
        }
        val fraction = active.toDouble() / (endBeatExclusive - startBeat - 1)
        if (fraction < 0.5) issues += AcousticPulseIssue.INSUFFICIENT_LOCAL_ATTACKS
        return AcousticPulseRangeAssessment(
            startBeat,
            endBeatExclusive,
            issues.isEmpty(),
            issues.toSet(),
            fraction,
        )
    }
}

/** Local recurrence assessment of measured attack profiles on an immutable proposed clock. */
object AcousticPulseEvidence {
    const val MINIMUM_CONTRAST: Double = 0.005
    private const val WINDOW = 8
    private const val BINS = 32
    private const val BANDS = 4
    private const val PERMUTATIONS = 255

    /**
     * The conditional circular-shift null is a recurrence diagnostic on the supplied clock, not a
     * calibrated correctness test when that clock was estimated from the same audio. Quiet gain
     * scaling cancels before this assessment. Working storage is bounded by eight profiles and 56
     * circular correlations, plus returned results.
     */
    fun assess(
        features: AcousticAttackFeatures,
        beats: List<Beat>,
        cancellationCheck: () -> Unit = {},
    ): AcousticPulseReport {
        cancellationCheck()
        var insideMeasuredDuration = true
        var strictlyIncreasing = true
        var previous = Double.NEGATIVE_INFINITY
        var beatIndex = 0
        val beatIterator = beats.iterator()
        while (beatIterator.hasNext()) {
            if (beatIndex > 0 && beatIndex % 256 == 0) cancellationCheck()
            val seconds = beatIterator.next().seconds
            if (!seconds.isFinite() || seconds < 0.0 || seconds > features.durationSeconds)
                insideMeasuredDuration = false
            if (beatIndex > 0 && seconds <= previous) strictlyIncreasing = false
            previous = seconds
            beatIndex++
        }
        require(insideMeasuredDuration) {
            "Beat observations must be finite and inside the measured source duration"
        }
        require(strictlyIncreasing) {
            "Beat observations must be strictly increasing"
        }
        val intervalCount = (beats.size - 1).coerceAtLeast(0)
        val contrasts = DoubleArray(intervalCount)
        val profiles = Array(WINDOW) { DoubleArray(BANDS * BINS) }
        val normSquares = DoubleArray(WINDOW)
        val correlations = DoubleArray(WINDOW * (WINDOW - 1) * BINS)
        val medianWork = DoubleArray(BINS)
        val windows = ArrayList<AcousticPulseWindow>((intervalCount - WINDOW + 1).coerceAtLeast(0))
        val pairOlder = IntArray(WINDOW * (WINDOW - 1) / 2)
        val pairNewer = IntArray(pairOlder.size)
        val pairBase = IntArray(pairOlder.size)
        for (index in 0 until intervalCount) {
            cancellationCheck()
            val profile = profiles[index % WINDOW]
            val start = beats[index].seconds
            val period = beats[index + 1].seconds - start
            var contrast = 0.0
            var norm = 0.0
            for (band in 0 until BANDS) {
                for (bin in 0 until BINS) {
                    val value = features.interpolate(band, start + (bin + 0.5) / BINS * period)
                    profile[band * BINS + bin] = value
                    medianWork[bin] = value
                }
                medianWork.sort()
                val median = (medianWork[BINS / 2 - 1] + medianWork[BINS / 2]) * 0.5
                for (bin in 0 until BINS) {
                    val location = band * BINS + bin
                    val value = max(0.0, profile[location] - median)
                    profile[location] = value
                    contrast = max(contrast, value)
                    norm += value * value
                }
            }
            check(contrast.isFinite() && norm.isFinite()) { "Nonfinite attack profile" }
            contrasts[index] = contrast
            val active = contrast >= MINIMUM_CONTRAST
            if (active) {
                val scale = sqrt(norm)
                for (bin in profile.indices) profile[bin] /= scale
            } else {
                profile.fill(0.0)
            }
            normSquares[index % WINDOW] = profile.sumOf { it * it }
            for (older in max(0, index - WINDOW + 1) until index) {
                val previous = profiles[older % WINDOW]
                val base = (older % WINDOW * (WINDOW - 1) + index - older - 1) * BINS
                for (shift in 0 until BINS) {
                    var product = 0.0
                    for (band in 0 until BANDS) {
                        val bandBase = band * BINS
                        for (bin in 0 until BINS) {
                            product +=
                                previous[bandBase + bin] *
                                    profile[bandBase + (bin - shift + BINS) % BINS]
                        }
                    }
                    correlations[base + shift] = product
                }
            }
            if (index + 1 < WINDOW) continue
            val first = index + 1 - WINDOW
            var diagonal = 0.0
            var activeCount = 0
            for (offset in 0 until WINDOW) {
                diagonal += normSquares[(first + offset) % WINDOW]
                if (contrasts[first + offset] >= MINIMUM_CONTRAST) activeCount++
            }
            var observed = diagonal
            var pair = 0
            for (older in 0 until WINDOW - 1) for (newer in older + 1 until WINDOW) {
                val base = ((first + older) % WINDOW * (WINDOW - 1) + newer - older - 1) * BINS
                pairOlder[pair] = older
                pairNewer[pair] = newer
                pairBase[pair] = base
                observed += 2.0 * correlations[base]
                pair++
            }
            observed /= WINDOW * WINDOW
            var atLeastObserved = 0
            var nullSum = 0.0
            var nullSumSquares = 0.0
            for (permutation in 0 until PERMUTATIONS) {
                if (permutation % 32 == 0) cancellationCheck()
                var shuffled = diagonal
                val shiftBase = permutation * WINDOW
                for (p in pairOlder.indices) {
                    val shift =
                        (FIXED_SHIFTS[shiftBase + pairNewer[p]] -
                            FIXED_SHIFTS[shiftBase + pairOlder[p]] + BINS) % BINS
                    shuffled += 2.0 * correlations[pairBase[p] + shift]
                }
                shuffled /= WINDOW * WINDOW
                check(shuffled.isFinite()) { "Nonfinite circular-shift statistic" }
                if (shuffled >= observed - 1e-12) atLeastObserved++
                nullSum += shuffled
                nullSumSquares += shuffled * shuffled
            }
            check(observed.isFinite()) { "Nonfinite recurrence statistic" }
            val pValue = (atLeastObserved + 1.0) / (PERMUTATIONS + 1.0)
            val fraction = activeCount.toDouble() / WINDOW
            val nullMean = nullSum / PERMUTATIONS
            val nullStd = sqrt(max(0.0, nullSumSquares / PERMUTATIONS - nullMean * nullMean))
            windows +=
                AcousticPulseWindow(
                    first,
                    first + WINDOW + 1,
                    beats[first].seconds,
                    beats[first + WINDOW].seconds,
                    fraction,
                    observed,
                    nullMean,
                    nullStd,
                    pValue,
                    fraction >= 0.5 && pValue <= 0.01,
                )
        }
        cancellationCheck()
        return AcousticPulseReport(
            DoubleArray(beats.size) { beats[it].seconds },
            windows,
            contrasts,
        )
    }

    // Frozen NumPy default_rng(12499).integers(0,32,size=(255,8)); never substitute
    // Kotlin Random: a different null sample can change a discrete threshold decision.
    private val FIXED_SHIFTS =
        intArrayOf(
            0,
            26,
            21,
            14,
            22,
            12,
            24,
            31,
            24,
            17,
            13,
            14,
            2,
            23,
            23,
            21,
            12,
            19,
            24,
            16,
            23,
            19,
            28,
            25,
            21,
            20,
            0,
            6,
            7,
            26,
            9,
            1,
            10,
            14,
            29,
            16,
            10,
            30,
            14,
            20,
            30,
            5,
            4,
            5,
            27,
            22,
            8,
            26,
            1,
            4,
            8,
            22,
            27,
            25,
            27,
            17,
            18,
            8,
            5,
            26,
            4,
            15,
            3,
            17,
            1,
            23,
            19,
            11,
            15,
            27,
            5,
            15,
            3,
            21,
            31,
            8,
            19,
            10,
            12,
            19,
            5,
            22,
            18,
            13,
            16,
            18,
            27,
            26,
            24,
            13,
            14,
            27,
            12,
            5,
            6,
            20,
            5,
            15,
            8,
            8,
            26,
            2,
            21,
            30,
            0,
            27,
            24,
            29,
            29,
            2,
            8,
            14,
            23,
            30,
            1,
            24,
            31,
            31,
            21,
            16,
            5,
            1,
            21,
            31,
            17,
            5,
            12,
            20,
            4,
            0,
            4,
            6,
            14,
            30,
            3,
            12,
            8,
            5,
            20,
            24,
            23,
            9,
            12,
            12,
            28,
            30,
            29,
            16,
            26,
            27,
            30,
            23,
            25,
            5,
            15,
            23,
            17,
            11,
            21,
            28,
            10,
            15,
            14,
            19,
            17,
            7,
            13,
            5,
            0,
            22,
            21,
            24,
            18,
            7,
            30,
            21,
            1,
            4,
            0,
            23,
            20,
            13,
            7,
            4,
            21,
            8,
            17,
            28,
            11,
            13,
            3,
            20,
            30,
            22,
            31,
            0,
            23,
            21,
            1,
            8,
            29,
            26,
            8,
            12,
            19,
            11,
            8,
            13,
            25,
            23,
            4,
            12,
            6,
            22,
            24,
            28,
            26,
            22,
            17,
            5,
            31,
            21,
            15,
            8,
            7,
            1,
            22,
            30,
            28,
            9,
            10,
            10,
            15,
            28,
            22,
            21,
            0,
            23,
            18,
            11,
            8,
            31,
            18,
            20,
            15,
            21,
            23,
            17,
            1,
            27,
            14,
            7,
            19,
            24,
            5,
            1,
            28,
            13,
            25,
            27,
            4,
            7,
            30,
            1,
            5,
            29,
            27,
            30,
            4,
            10,
            20,
            15,
            11,
            5,
            27,
            19,
            8,
            10,
            9,
            31,
            30,
            9,
            11,
            20,
            7,
            0,
            11,
            14,
            1,
            9,
            8,
            28,
            13,
            12,
            21,
            22,
            22,
            0,
            21,
            27,
            14,
            4,
            8,
            12,
            7,
            10,
            24,
            13,
            9,
            14,
            5,
            15,
            8,
            26,
            22,
            22,
            30,
            4,
            21,
            20,
            31,
            2,
            6,
            17,
            13,
            5,
            21,
            22,
            14,
            4,
            13,
            11,
            27,
            25,
            18,
            29,
            2,
            19,
            9,
            9,
            3,
            22,
            7,
            8,
            23,
            15,
            1,
            21,
            25,
            5,
            30,
            3,
            0,
            13,
            16,
            26,
            1,
            19,
            5,
            14,
            25,
            30,
            30,
            31,
            31,
            29,
            4,
            21,
            8,
            9,
            12,
            27,
            19,
            25,
            27,
            17,
            12,
            31,
            5,
            10,
            20,
            8,
            6,
            21,
            1,
            9,
            11,
            13,
            16,
            27,
            20,
            4,
            5,
            23,
            19,
            30,
            26,
            24,
            6,
            28,
            15,
            21,
            28,
            10,
            1,
            2,
            13,
            7,
            5,
            3,
            28,
            19,
            28,
            8,
            0,
            19,
            11,
            2,
            29,
            28,
            10,
            13,
            16,
            1,
            9,
            17,
            28,
            25,
            4,
            26,
            31,
            5,
            1,
            1,
            20,
            17,
            8,
            20,
            6,
            25,
            14,
            16,
            22,
            21,
            2,
            11,
            26,
            4,
            15,
            6,
            7,
            15,
            27,
            31,
            31,
            16,
            6,
            28,
            11,
            4,
            28,
            29,
            14,
            5,
            18,
            23,
            0,
            0,
            13,
            21,
            16,
            13,
            28,
            25,
            28,
            28,
            21,
            7,
            21,
            30,
            16,
            7,
            19,
            16,
            6,
            8,
            0,
            22,
            19,
            12,
            25,
            9,
            19,
            22,
            29,
            9,
            1,
            22,
            21,
            19,
            1,
            9,
            22,
            18,
            21,
            12,
            6,
            26,
            31,
            8,
            24,
            4,
            19,
            24,
            27,
            15,
            15,
            15,
            1,
            0,
            12,
            30,
            19,
            21,
            18,
            29,
            12,
            31,
            23,
            12,
            29,
            27,
            15,
            11,
            21,
            6,
            21,
            17,
            26,
            26,
            23,
            4,
            14,
            1,
            6,
            4,
            15,
            31,
            8,
            31,
            7,
            24,
            22,
            14,
            11,
            31,
            0,
            12,
            14,
            16,
            7,
            21,
            9,
            21,
            3,
            11,
            18,
            9,
            27,
            24,
            6,
            1,
            16,
            9,
            0,
            9,
            21,
            4,
            5,
            11,
            10,
            14,
            6,
            6,
            12,
            5,
            14,
            4,
            29,
            29,
            30,
            27,
            7,
            26,
            2,
            6,
            18,
            29,
            9,
            19,
            26,
            7,
            17,
            6,
            3,
            26,
            30,
            8,
            11,
            7,
            22,
            10,
            10,
            6,
            31,
            29,
            8,
            12,
            13,
            15,
            7,
            23,
            4,
            5,
            21,
            28,
            26,
            25,
            20,
            5,
            6,
            30,
            30,
            8,
            0,
            9,
            27,
            13,
            12,
            17,
            14,
            29,
            29,
            25,
            11,
            30,
            26,
            26,
            30,
            5,
            30,
            1,
            6,
            0,
            14,
            28,
            2,
            31,
            24,
            14,
            31,
            5,
            29,
            4,
            10,
            15,
            23,
            7,
            31,
            12,
            18,
            1,
            18,
            5,
            14,
            30,
            26,
            0,
            16,
            10,
            4,
            29,
            26,
            27,
            22,
            9,
            24,
            25,
            31,
            28,
            9,
            25,
            7,
            13,
            23,
            26,
            24,
            5,
            16,
            0,
            15,
            24,
            24,
            26,
            10,
            8,
            14,
            17,
            29,
            29,
            3,
            5,
            28,
            19,
            24,
            24,
            0,
            25,
            26,
            7,
            12,
            3,
            5,
            28,
            22,
            15,
            9,
            30,
            27,
            11,
            30,
            1,
            8,
            25,
            1,
            28,
            18,
            13,
            16,
            8,
            27,
            26,
            9,
            18,
            28,
            13,
            3,
            13,
            27,
            10,
            13,
            1,
            24,
            14,
            28,
            13,
            18,
            2,
            17,
            25,
            31,
            10,
            0,
            9,
            5,
            0,
            9,
            9,
            21,
            18,
            19,
            19,
            22,
            1,
            1,
            8,
            24,
            18,
            11,
            29,
            7,
            23,
            10,
            25,
            18,
            6,
            19,
            18,
            13,
            17,
            12,
            10,
            16,
            8,
            10,
            18,
            22,
            22,
            17,
            1,
            18,
            5,
            16,
            8,
            14,
            0,
            8,
            27,
            14,
            8,
            29,
            23,
            25,
            13,
            0,
            14,
            24,
            27,
            8,
            29,
            9,
            15,
            15,
            17,
            22,
            18,
            0,
            6,
            30,
            9,
            23,
            27,
            21,
            0,
            29,
            4,
            9,
            10,
            2,
            11,
            22,
            11,
            4,
            11,
            21,
            26,
            0,
            14,
            13,
            0,
            4,
            1,
            31,
            8,
            1,
            18,
            14,
            27,
            14,
            7,
            6,
            1,
            20,
            23,
            15,
            25,
            30,
            30,
            5,
            24,
            11,
            22,
            14,
            1,
            28,
            27,
            0,
            18,
            31,
            25,
            10,
            29,
            31,
            15,
            12,
            20,
            28,
            30,
            0,
            25,
            5,
            15,
            18,
            11,
            23,
            19,
            10,
            3,
            26,
            0,
            20,
            20,
            23,
            24,
            12,
            12,
            9,
            8,
            27,
            29,
            13,
            5,
            31,
            21,
            13,
            24,
            22,
            13,
            0,
            4,
            10,
            21,
            23,
            31,
            3,
            29,
            28,
            0,
            2,
            24,
            7,
            21,
            26,
            0,
            29,
            6,
            19,
            20,
            23,
            22,
            19,
            13,
            6,
            4,
            22,
            28,
            23,
            28,
            29,
            28,
            9,
            19,
            7,
            29,
            30,
            0,
            21,
            20,
            13,
            24,
            6,
            30,
            27,
            14,
            4,
            17,
            19,
            3,
            22,
            21,
            27,
            9,
            16,
            20,
            11,
            25,
            17,
            23,
            4,
            15,
            3,
            10,
            7,
            31,
            28,
            14,
            25,
            7,
            30,
            31,
            28,
            9,
            23,
            1,
            29,
            8,
            28,
            18,
            1,
            31,
            1,
            1,
            9,
            13,
            10,
            26,
            13,
            20,
            10,
            15,
            22,
            16,
            22,
            6,
            16,
            16,
            1,
            28,
            5,
            29,
            2,
            15,
            6,
            17,
            30,
            13,
            17,
            30,
            27,
            8,
            23,
            2,
            27,
            22,
            26,
            15,
            21,
            9,
            2,
            13,
            27,
            19,
            31,
            10,
            25,
            26,
            15,
            20,
            7,
            14,
            0,
            30,
            28,
            18,
            19,
            9,
            7,
            15,
            7,
            26,
            10,
            20,
            20,
            21,
            30,
            22,
            7,
            25,
            0,
            17,
            0,
            4,
            29,
            7,
            28,
            23,
            6,
            0,
            21,
            0,
            28,
            1,
            7,
            16,
            9,
            8,
            31,
            14,
            14,
            6,
            2,
            16,
            30,
            11,
            8,
            10,
            4,
            27,
            1,
            9,
            16,
            24,
            31,
            20,
            15,
            14,
            17,
            30,
            16,
            11,
            4,
            8,
            0,
            27,
            18,
            31,
            9,
            5,
            0,
            10,
            25,
            17,
            2,
            25,
            25,
            6,
            6,
            24,
            1,
            1,
            4,
            30,
            18,
            30,
            27,
            30,
            10,
            12,
            4,
            25,
            26,
            30,
            20,
            2,
            13,
            24,
            12,
            4,
            17,
            13,
            16,
            21,
            12,
            10,
            8,
            27,
            14,
            6,
            9,
            14,
            15,
            17,
            11,
            13,
            4,
            20,
            11,
            9,
            1,
            27,
            29,
            25,
            13,
            30,
            4,
            6,
            25,
            0,
            15,
            20,
            0,
            19,
            9,
            14,
            25,
            10,
            10,
            0,
            4,
            8,
            15,
            16,
            25,
            28,
            17,
            21,
            17,
            6,
            23,
            25,
            12,
            20,
            0,
            22,
            0,
            2,
            3,
            14,
            20,
            28,
            1,
            23,
            31,
            13,
            12,
            15,
            19,
            29,
            6,
            11,
            0,
            29,
            4,
            3,
            0,
            15,
            27,
            10,
            7,
            16,
            16,
            6,
            21,
            31,
            8,
            4,
            18,
            2,
            23,
            22,
            29,
            29,
            0,
            4,
            15,
            28,
            3,
            30,
            26,
            28,
            20,
            2,
            2,
            20,
            24,
            0,
            31,
            2,
            23,
            17,
            24,
            7,
            27,
            29,
            1,
            29,
            9,
            25,
            0,
            21,
            26,
            30,
            12,
            7,
            28,
            29,
            1,
            2,
            17,
            12,
            2,
            12,
            11,
            25,
            13,
            12,
            18,
            29,
            9,
            20,
            15,
            17,
            6,
            5,
            25,
            25,
            30,
            9,
            7,
            25,
            20,
            28,
            5,
            23,
            20,
            10,
            21,
            22,
            9,
            8,
            20,
            13,
            28,
            26,
            28,
            1,
            28,
            15,
            22,
            10,
            18,
            28,
            6,
            16,
            24,
            14,
            10,
            15,
            0,
            14,
            0,
            5,
            27,
            3,
            2,
            24,
            1,
            27,
            11,
            15,
            21,
            25,
            21,
            4,
            16,
            10,
            22,
            18,
            16,
            28,
            13,
            14,
            27,
            7,
            30,
            4,
            6,
            10,
            0,
            18,
            29,
            11,
            11,
            1,
            10,
            1,
            24,
            19,
            9,
            8,
            4,
            30,
            24,
            9,
            24,
            2,
            29,
            4,
            20,
            6,
            23,
            13,
            25,
            21,
            4,
            12,
            17,
            6,
            24,
            22,
            20,
            9,
            19,
            29,
            23,
            29,
            16,
            11,
            5,
            19,
            29,
            4,
            20,
            16,
            8,
            26,
            1,
            17,
            1,
            4,
            31,
            15,
            14,
            28,
            31,
            5,
            31,
            31,
            13,
            0,
            23,
            11,
            18,
            13,
            11,
            2,
            30,
            18,
            30,
            29,
            9,
            27,
            22,
            26,
            22,
            30,
            23,
            9,
            23,
            1,
            15,
            28,
            1,
            11,
            18,
            30,
            7,
            11,
            26,
            2,
            28,
            3,
            9,
            2,
            31,
            6,
            3,
            28,
            15,
            21,
            27,
            11,
            0,
            18,
            23,
            17,
            16,
            19,
            17,
            21,
            12,
            8,
            5,
            14,
            23,
            4,
            30,
            11,
            0,
            28,
            22,
            21,
            6,
            12,
            19,
            2,
            21,
            11,
            20,
            17,
            27,
            1,
            23,
            7,
            22,
            28,
            13,
            7,
            23,
            21,
            12,
            8,
            12,
            15,
            3,
            7,
            29,
            18,
            22,
            11,
            0,
            14,
            9,
            13,
            18,
            2,
            9,
            12,
            24,
            22,
            3,
            8,
            21,
            19,
            2,
            7,
            19,
            3,
            28,
            3,
            18,
            14,
            2,
            20,
            9,
            3,
            9,
            28,
            27,
            8,
            0,
            20,
            11,
            13,
            28,
            22,
            16,
            18,
            0,
            1,
            10,
            10,
            26,
            20,
            28,
            6,
            11,
            14,
            30,
            17,
            5,
            26,
            19,
            26,
            12,
            29,
            7,
            28,
            1,
            11,
            15,
            2,
            27,
            31,
            31,
            18,
            9,
            30,
            10,
            0,
            28,
            23,
            9,
            13,
            26,
            15,
            7,
            9,
            5,
            2,
            1,
            20,
            22,
            28,
            21,
            6,
            28,
            4,
            29,
            14,
            9,
            22,
            0,
            1,
            28,
            29,
            10,
            5,
            7,
            4,
            17,
            30,
            22,
            11,
            12,
            20,
            29,
            17,
            24,
            18,
            2,
            14,
            28,
            26,
            28,
            7,
            26,
            3,
            25,
            28,
            29,
            11,
            14,
            4,
            16,
            21,
            5,
            14,
            22,
            3,
            16,
            6,
            14,
            31,
            29,
            9,
            10,
            18,
            30,
            22,
            16,
            19,
            22,
            29,
            31,
            23,
            3,
            30,
            26,
            20,
            5,
            5,
            9,
            12,
            23,
            0,
            19,
            16,
            8,
            15,
            1,
            17,
            11,
            10,
            23,
            27,
            24,
            25,
            23,
            3,
            8,
            16,
            21,
            13,
            3,
            31,
            31,
            31,
            12,
            15,
            11,
            6,
            20,
            25,
            10,
            8,
            11,
            12,
            21,
            11,
            24,
            0,
            15,
            1,
            3,
            15,
            21,
            6,
            23,
            19,
            26,
            3,
            23,
            17,
            15,
            25,
            0,
            27,
            27,
            1,
            16,
            24,
            1,
            18,
            15,
            3,
            10,
            2,
            11,
            25,
            2,
            26,
            28,
            17,
            5,
            21,
            26,
            11,
            14,
            28,
            1,
            12,
            3,
            8,
            30,
            18,
            31,
            27,
            1,
            4,
            17,
            15,
            16,
            24,
            16,
            10,
            19,
            8,
            9,
            18,
            27,
            9,
            30,
            23,
            9,
            10,
            0,
            0,
            24,
            28,
            19,
            5,
            15,
            13,
            2,
            14,
            31,
            15,
            27,
            31,
            0,
            31,
            31,
            25,
            28,
            21,
            19,
            28,
            15,
            16,
            12,
            4,
            15,
            14,
            24,
            10,
            14,
            26,
            6,
            12,
            8,
            23,
            17,
            22,
            2,
            9,
            10,
            26,
            0,
            27,
            7,
            10,
            11,
            11,
            5,
            26,
            9,
            19,
            16,
            31,
            22,
            4,
            16,
            15,
            5,
            29,
            11,
            21,
            14,
            20,
            0,
            19,
            14,
            27,
            21,
            18,
            23,
            2,
            11,
            14,
            23,
            8,
            17,
            12,
            7,
            24,
            3,
            25,
            21,
            2,
            15,
            7,
            9,
            28,
            11,
            25,
            20,
            29,
            30,
            21,
            16,
            14,
            1,
            27,
            2,
            29,
            23,
            20,
            23,
            13,
            7,
            8,
            27,
            0,
            0,
            5,
            5,
            0,
            24,
            21,
            6,
            9,
            15,
            31,
            4,
            14,
            12,
            26,
            30,
            6,
            6,
            19,
            3,
            13,
            7,
            22,
            15,
            10,
            11,
            2,
            0,
            17,
            11,
            13,
            19,
            22,
            21,
            5,
            17,
            7,
            13,
            18,
            16,
            12,
            31,
            7,
            16,
            1,
            20,
            31,
            24,
            18,
            8,
            4,
            25,
            24,
            27,
            9,
            5,
            5,
            5,
            8,
            9,
            28,
            11,
            31,
            14,
            25,
            18,
            4,
            28,
            7,
            7,
            5,
            19,
            10,
            25,
            11,
            9,
            28,
            30,
            3,
            18,
            7,
            13,
            16,
            16,
            0,
            14,
            31,
            1,
            23,
            31,
            4,
            3,
            26,
            11,
            16,
            28,
            0,
            5,
            27,
            21,
            1,
            8,
            29,
            8,
            27,
            26,
            10,
            30,
            18,
            22,
            10,
            19,
            27,
            8,
            22,
            11,
            2,
            7,
            9,
            15,
            7,
            24,
            16,
            30,
            12,
            26,
            29,
            2,
            4,
            8,
            27,
            13,
            17,
            31,
            15,
            1,
            15,
            24,
            1,
            21,
            17,
            31,
            3,
            12,
            25,
            31,
            31,
            23,
            17,
            23,
            26,
            20,
            16,
            30,
            0,
            22,
            4,
            30,
            13,
            27,
            17,
            7,
            19,
            27,
            1,
            7,
            22,
        )
}
